### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zarnaagames** [alebianco/ANE-Google-Analytics#21]
HI.
I am implementing google analytics in my game. But its behaviour is strange.
In sample application which I created its working. But same code in my game is not dispatching any thing. In debug mode it prints 'Dsipatch running...noting to dispatch...'

Please let me know if I am doing anything wrong.

I am compiling with AIR SDK 3.5 on windows and 3.8 on MAC.

Waiting to hear from you
Thanks

**Comment by alebianco** [comment]
This doesn't look like a bug report to me.
Try to give me some specific information, like which version of the extension are you using, on which platform you're deploying and such.
Also, if you previously created a sample app that was working, there's a good chance that problem lies in your code and not the extension itself.

**Comment by zarnaagames** [comment]
Its fixed.
Thanks for quick reply. I forgot to add line tracker.buildview()...thats
why it was not dispatching anythng.
Now its working.

Thanks man

On Thu, Sep 26, 2013 at 5:23 PM, Alessandro Bianco <notifications@github.com
