### ISSUE TITLE
Clarification required on some API usage.

### ISSUE THREAD

**Issue by Eternalspirit** [alebianco/ANE-Google-Analytics#24]
Hey there,

Nice thing you have here, but I'm very confused about how some of the API works. I understand (well.. sort of) something like tracker.buildView("Home").track(); (simply sends a response to the server that the user visited a page and to give it the "Home" label in the analytics page), but others are not so obvious. For example:

tracker.buildEvent("swipe", "screen").withValue(1).track();
tracker.buildTiming("loading", 5000).withName("resources").withLabel("audio.mp3").track();

I understand the concept of what these are supposed to do, what I don't understand is what all the values and function calls actually mean or do. It would be nice if there were ASDocs available detailing exactly what the functions do and what constants are available for use in the API, along with what they mean.

Thanks.

**Comment by alebianco** [comment]
I guess some basic understanding of google analytics is required in order to use it :)
The extension in only providing a fluent and streamlined API to expose the Google Analytics SDK in AIR
I agree that the docs can be more exaustive but it's not my focus at the moment, considering that everything is covered in detail by Google's doc pages ( like https://developers.google.com/analytics/devguides/collection/android/v2/)

**Comment by Eternalspirit** [comment]
Hmm.. I do notice some links to advanced stuff at the bottom there, so I will check it out! And I'm assuming the constants used in the API are available in the source code, so I will check that out as well!

Yeah, I sort of just got thrust into doing this for my work, and I have zero experience with GA. Guess I will just have to learn on the fly!

**Comment by alebianco** [comment]
It's not too complex even for a new starter. Have a look at the Analytics dashboard and the official Google documentation, it's pretty clear.
The extension allows you to do (most of) the same things, just with a slightly different sintax.
