### ISSUE TITLE
buildSocial doesnt seem to work

### ISSUE THREAD

**Issue by doronkatz** [alebianco/ANE-Google-Analytics#27]
Hey mate,

So im trying on both iOS and Android to track
tracker.buildSocial("Facebook", "like").forContent(currentVideo.title).track();

Whilst the other analytics work, i dont seem to get anything for that. Not sure if i am doing it the right way, and i noticed on your example you dont have the forContent part, but having tested for both this and twitter, it doesnt seem to trigger.

**Comment by alebianco** [comment]
have you tried without the content as well?
also, you get anything from the device log? error reports, warnings, whatever ...

**Comment by QasimQureshi** [comment]
Wish there was a way to test this extension in code, like a debug panel. 

I've added the ANE to my project(not the SWC, as instructed in the documentation), copy/pasted the import eu.alebianco ... tracker.buildView("Home").track(); 

When I go to the Analytics dashboard, in Real-time>Events, nothing shows. Not sure what's wrong. In the analytics dashboard, I'd set the app up as a "mobile app" rather than a "web app".

**Comment by alebianco** [comment]
sorry about the delay but as you can see from the [screenshot](https://www.dropbox.com/s/8kktylvffd7czfs/Screenshot%202014-01-14%2015.33.40.png) the social media events are reported correctly from both android and ios with both set and unset media content

just be aware that social events are not regular events, you'll need to setup a custom dashboard to see them (or at least it's the only way i found to see them)

@QasimQureshi if you want to ask for an improvement not related to the original issue, open a different one and let's discuss about that
