### ISSUE TITLE
[Feature Request] Add currency code to TransactionBuilder

### ISSUE THREAD

**Issue by EljoB** [alebianco/ANE-Google-Analytics#28]
It would be great to have support for multiple currencies when tracking mobile in-app-purchases. It seems like Google has added this feature to their own SDKs for both Android and iOS so it should be possible to wrap around it.

**Comment by alebianco** [comment]
thanks for pointing that out, I didn't noticed they had added that new property.
I've added a task on trello for this change.
The work to support the new SDK is already in progress so this will be done as soon as the rest of the integration is ready, at some point in January probably ...

**Comment by fwal** [comment]
Hi, 
I'm also interested in this and by the new SDK, do you mean the new analytics sdk? Any ETA?

**Comment by alebianco** [comment]
There's a "half implementation" for the current sdk (2.0.x) since Google added the feature only on the android library.
I hope to be able to give full support when I release the support for the new sdk (3.x).

I'm not going to give any ETA, but i'm testing the next iteration of the current release. It will be release when i can fix the last issues but if you want i can publish a pre-release already.

For the next version I already did some work but I need to review and test what i did and there're a couple more features i want to add ... also i'm not doing any of that while i'm testing the current one. In other words: it will take some time.
