### ISSUE TITLE
NativeGATracker-v2.0.4.ane [META-INF/ANE/extension.xml]: error 102: Invalid namespace http://ns.adobe.com/air/extension/4.0

### ISSUE THREAD

**Issue by ebhoren** [alebianco/ANE-Google-Analytics#37]
Error when compiling my application with AIR 3.7 using FB 4.7. I'm using release build v2.0.4.

Any ideas how to solve this?
Thanks

**Comment by aduros** [comment]
Upgrade to AIR 4.0?

**Comment by ebhoren** [comment]
Not an option on the project i'm working on.

**Comment by alebianco** [comment]
In order to support the latest AIR i cannot downgrade the namespace for the extension. And i cannot downgrade the version of AIR supported since it will block any app being released for iOS.

You have 2 choices: 
1) use an earlier version of the extension, and lose some features
2) check out the code, change the extension namespace and build your own version (kindly brought to you by the gods of opensource)

**Comment by ebhoren** [comment]
I've use option 2 and it work.
Thanks
